In [6]:
import pandas as pd
import pickle

import torch
from torchvision import models, transforms
from PIL import Image
import numpy as np

import tensorflow as tf
import h5py
import numpy as np

In [2]:
csv_file_path = 'C:/Users/96446/Documents/GitHub/learning Pytorch/pytorch/FB15K_Updated.csv'

df = pd.read_csv(csv_file_path)

entity_type_counts = df['Entity Type'].value_counts()
filtered_entity_type_counts = entity_type_counts[entity_type_counts >= 2]

print(filtered_entity_type_counts)

Entity Type
human                           4495
film                            1659
association football club        608
city                             330
music genre                      328
                                ... 
university college                 2
university in France               2
lieutenancy area of Scotland       2
bicameral legislature              2
dialect                            2
Name: count, Length: 581, dtype: int64


In [64]:
pkl_file_path  = 'C:/Users\96446\Documents\GitHub\data\mmkg\pkls/FBDB15K_id_img_feature_dict.pkl'
# 用pickle加载数据
with open(pkl_file_path, 'rb') as file:
    data = pickle.load(file)

# 检查数据的类型
print(type(data))

<class 'dict'>


In [67]:
data[0]

array([1.3076725, 1.2305019, 1.5317996, ..., 0.       , 2.080137 ,
       0.       ], dtype=float32)

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class ImageFeatureMapper(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(ImageFeatureMapper, self).__init__()
        # 定义图像特征映射到新空间的线性层
        self.img_fc = nn.Linear(input_dim, output_dim)

    def forward(self, img_features):
        # 应用线性层并返回映射后的特征
        img_emb = self.img_fc(img_features)
        return img_emb

input_dim = 4096  # 原始图像特征维度
output_dim = 300  # 目标映射维度
model = ImageFeatureMapper(input_dim, output_dim)

# 假设我们有一个图像特征Tensor
img_features = torch.randn(1, 4096)  # 示例输入，假设批大小为1

# 将图像特征映射到300维空间
img_emb = model(img_features)
print("Mapped image features shape:", img_emb.shape)

C:\Users\96446\anaconda3\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\96446\anaconda3\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to C:\Users\96446/.cache\torch\hub\checkpoints\vgg16-397923af.pth
100%|██████████| 528M/528M [00:42<00:00, 12.9MB/s] 


FileNotFoundError: [Errno 2] No such file or directory: 'image_path.jpg'

In [69]:
img_features = torch.randn(1, 4096)
img_features

tensor([[ 0.4554, -0.3123,  2.6431,  ...,  2.1465,  0.8970,  0.1708]])

In [37]:
vgg16_h5 = 'FB15K_ImageData.h5'
f = h5py.File(vgg16_h5, 'r')
vgg_feats = f[("FBIMG00001")]

vgg_feats_np = np.array(vgg_feats)
print(vgg_feats_np)

0.0


In [44]:
image_index = 'FB15K/FB15K_ImageIndex.txt'
result = {}
with open(image_index, 'r') as fr:
    for img_id in fr:
        value = img_id.split()
        result[value[0]] = value[1]

In [46]:
result

KeyError: 0

In [70]:
vgg16_h5 = 'FB15K_ImageData.h5'

result2 = {}
for key, value in result.items():
    f = h5py.File(vgg16_h5, 'r')
    result2[key] = [np.array(f[(value)])]
    
result2['/m/01m4kpp'][1]

IndexError: list index out of range

In [71]:
result2['/m/01m4kpp'][0]

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.5510511]], dtype=float32)